### ISSUE TITLE
What are the differences between this and the default template

### ISSUE THREAD

**Issue by ssipos90** [johnsoncodehk/volar-starter#2]
Hi,

How is this template different specifically?

Tnx

**Comment by johnsoncodehk** [comment]
It just preset some settings to show Volar as recommend, enable TS plugin and add `vue-tsc` for command line type-checking.

But vite template also add `vue-tsc` now, I actually plan to deprecate this template, and direction to vite template.

- https://github.com/johnsoncodehk/volar-starter/blob/f03c2e48ca580a715af9f28215774ca65b85f025/.vscode/extensions.json#L3
- https://github.com/johnsoncodehk/volar-starter/blob/f03c2e48ca580a715af9f28215774ca65b85f025/.vscode/settings.json#L2
- https://github.com/johnsoncodehk/volar-starter/blob/f03c2e48ca580a715af9f28215774ca65b85f025/package.json#L16

**Comment by ssipos90** [comment]
Thanks.
