### ISSUE TITLE
Issue with save and v-on

### ISSUE THREAD

**Issue by msires** [johnsoncodehk/volar-starter#4]
When saving a page with a v-on ="", the ="" is removed which causes errors.  If I change it to ="x", then it is not removed and saves and runs fun.  Volar v0.31.4, Microsoft Windows V11
Page example (from vueschool.io Pinia lessons)

//
<script setup> 

import { ref } from "vue";
import CartItem from "./CartItem.vue";
import { useCartStore } from "@/stores/CartStore";
const cartStore = useCartStore();

const active = ref(false);
</script>
<template>
  <div class="relative">

    <span class="cursor-pointer" @click="active = true">
      <fa icon="shopping-cart" size="lg" class="text-gray-700" />
      <div class="cart-count absolute">{{ cartStore.count }}</div>
    </span>
    <AppModalOverlay :active="active" @close="active = false">
      <div>
        <ul class="items-in-cart">
          <CartItem
            :product="{ name: 'Dried Pineapple', price: 5 }"
            :count="5"
            @updateCount="x"
            @clear="x"
          />
          <CartItem
            :product="{ name: 'Pineapple Gum', price: 3 }"
            :count="5"
            @updateCount="x"
            @clear="x"
          />
        </ul>
        <div class="flex justify-end text-2xl mb-5">
          Total:
          <strong>$40</strong>
        </div>
        <div class="flex justify-end">
          <AppButton class="secondary mr-2">Clear Cart</AppButton>
          <AppButton class="primary">Checkout</AppButton>
        </div>
      </div>
    </AppModalOverlay>
  </div>
</template>
<style lang="pcss" scoped>
.items-in-cart{
  @apply mb-5;
}
.items-in-cart li{
  @apply flex justify-between p-2;
}
.items-in-cart li:nth-of-type(even){
  @apply bg-gray-300;
}
</style>
//

**Comment by johnsoncodehk** [comment]
Hi @msires, this is expected behavior of [prettyhtml](https://github.com/Prettyhtml/prettyhtml). You could disable format on save to avoid.
