### ISSUE TITLE
Doesn't disable everything about Vetur

### ISSUE THREAD

**Issue by patarapolw** [johnsoncodehk/volar-starter#5]
Shouldn't volar-starter disable all of Vetur by default?

`/.vscode/settings.json`

```json
{
    "volar.tsPlugin": true,
    "volar.icon.preview": true,
    "volar.icon.finder": true,
    "vetur.validation.template": false,
    "vetur.validation.script": false,
    "vetur.validation.style": false,
}
```

I also noticed in `/.vscode/extensions.json`, there is

```json
{
    "unwantedRecommendations": [
        "octref.vetur"
    ]
}
```

I am not exactly sure if this one should be PR to Vue 3 / Vite upstream?

**Comment by johnsoncodehk** [comment]
Volar is default recommendation on vscode now, so there no needed any more configs, thanks.
