### ISSUE TITLE
There is no prompt for passing values to child components

### ISSUE THREAD

**Issue by xiangyuisabatman** [johnsoncodehk/volar-starter#8]
- volar: v0.37.9
- vue: 3.2.25
- typescript: 4.5.4
```
/**
* declare some props {labelWidth, popText, label}
*/
<template>
  <div
    class="label"
    :style="{ width: labelWidth + 'px', flex: `0 0 ${labelWidth}px` }"
  >
    {{ label }}
    <Popover v-if="popText" type="base" placement="top-left">
      <template #content>
        <article>
          {{ popText }}
        </article>/
      </template>
      <Icon class="icon" :name="'tagError'" />
    </Popover>
    :
  </div>
</template>

<script setup lang="ts">
interface Props {
  labelWidth: number; 
  popText: string; 
  label: string;
}
const props = withDefaults(defineProps<Props>(), {
  labelWidth: 140,
  popText: "",
  label: "",
});
</script>
```

There is no hint and no mandatory verification
![image](https://user-images.githubusercontent.com/23613080/174047084-9eefc507-ffcc-403e-b265-e0737ce5d105.png)

## hope
I want to know what parameters the child component has and is there anything missing

**Comment by johnsoncodehk** [comment]
Hi @xiangyuisabatman, I can't reproduce this problem in https://github.com/johnsoncodehk/volar-starter, please provide a minimal reproduction if you still have this problem with latest volar version.

<img width="429" alt="螢幕截圖 2022-07-07 11 14 40" src="https://user-images.githubusercontent.com/16279759/177683177-96d7920d-f062-4e97-84ac-44d846aaa722.png">
