### ISSUE TITLE
BUG: Closing tag linting issue in VS Studio

### ISSUE THREAD

**Issue by jmarshall9120** [johnsoncodehk/volar-starter#9]
The closing tags are coming up as unrecognized suddenly in templates, and none of the outputs in the console (ESLint, Prettier).  There is no specific output for volar that I see. 

![image](https://user-images.githubusercontent.com/30184747/186255170-6301189b-2a84-4a16-b16a-7c1c82be5f49.png)

I'm digging in.  It looks like Volar requires a jsconfig.json (which vuter did not).  I put that in, but no real change. Any ideas appreciated. 

I'm on:
Windows 11
Volar 0.40.1
Typescript Vue Plugin: 0.40.1 (not typescript in current project howerver)
VS Code: July 2022 (version 1.70)

**Comment by johnsoncodehk** [comment]
Please track https://github.com/johnsoncodehk/volar/issues/1756.
